### ISSUE TITLE
InventoryClickEvent to CrazyAuctionsPlus v1.1.4.3 && players can dupe items

### ISSUE THREAD

**Issue by iBuseWinner** [TRCStudioDean/CrazyAuctionsPlus#4]
Hi, getting that error in console:
`[12:34:20 ERROR]: Could not pass event InventoryClickEvent to CrazyAuctionsPlus v1.1.4.3
java.lang.NullPointerException: null
        at studio.trc.bukkit.crazyauctionsplus.event.GUIAction.onInvClick(GUIAction.java:621) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor929.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-375]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2381) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1232) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-375]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`
`[12:34:21 ERROR]: Could not pass event InventoryClickEvent to CrazyAuctionsPlus v1.1.4.3
org.yaml.snakeyaml.error.YAMLException: invalid string value has occurred
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentString.representData(SafeRepresenter.java:132) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:89) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representSequence(BaseRepresenter.java:134) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentList.representData(SafeRepresenter.java:190) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:38) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:38) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:24) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:24) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:271) ~[patched_1.15.2.jar:git-Paper-375]
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:246) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:94) ~[patched_1.15.2.jar:git-Paper-375]
        at studio.trc.bukkit.crazyauctionsplus.database.storage.YamlStorage.saveData(YamlStorage.java:233) ~[?:?]
        at studio.trc.bukkit.crazyauctionsplus.database.storage.YamlStorage.getMailBox(YamlStorage.java:159) ~[?:?]
        at studio.trc.bukkit.crazyauctionsplus.event.GUIAction.onInvClick(GUIAction.java:771) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor929.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-375]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2381) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-375]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

Using git-Paper-375 (MC: 1.15.2)
Can you fix it, please?

**Comment by mrjesen** [comment]
The author is a 12th grader,so he has no time to fix #4, and he had gave up this project. its so sad.
